#! /bin/sh
### BEGIN INIT INFO
# Provides:          nagixsc_http2nagios
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: Nag(IX)SC HTTP Push Server
# Description:       Nag(IX)SC HTTP Push Server
### END INIT INFO

# Author: Sven Velt <sv@teamix.net>

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/usr/sbin:/usr/bin:/sbin:/bin
DESC="Nag(IX)SC http2nagios"
NAME=nagixsc_http2nagios
DAEMONPATH=/usr/local/nagixsc
DAEMON=$DAEMONPATH/$NAME.py
CFGFILE=$DAEMONPATH/etc/http2nagios.cfg
DAEMON_ARGS="-c $CFGFILE"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Look for daemon and config file
if [ ! -r $DAEMON ]
then
	echo "Daemon not found, exiting..."
	exit 1
fi

if [ ! -r $CFGFILE ]
then
	echo "Config file not found, exiting..."
	exit 1
fi

is_running()
{
	[ -f "$PIDFILE" ] || return 1
	ps ax | grep "`cat $PIDFILE`" | grep $NAME | grep -qv grep
	return $?
}

do_start()
{
	is_running && return 1
	$DAEMON -d $DAEMON_ARGS || return 2
}

do_stop()
{
	is_running || return 1
	kill -TERM "`cat $PIDFILE`" 2>/dev/null
	sleep 1
	is_running || kill -KILL "`cat $PIDFILE`" 2>/dev/null
	if is_running
	then
		return 1
	fi
	rm -f $PIDFILE
}



case "$1" in
  start)
	echo -n "Starting $DESC ... "
	do_start
	case "$?" in
		0|1) echo $NAME ;;
		2) echo "$NAME did not start" ;;
	esac
	;;
  stop)
	echo -n "Stopping $DESC ... "
	do_stop
	if [ $? -eq 0 ]
	then
		echo "stopped"
	else
		echo "could NOT stop process!"
	fi
	;;
  restart|force-reload)
	echo -n "Restarting $DESC ... "
	do_stop
	sleep 1
	do_start
	echo "done"
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

